### PR TITLE
fix: wrong regex for wal retention

### LINKED ISSUE #1015: wal-g backup retention feature not working
## My finding
I set up wal-g on SSH to backup my patroni cluster. But I find the backup disk usage keep growing.

## Environment
spilo version: 3.3-p1
wal verion in dockerfile (unchanged): ENV WALG_VERSION=v3.0.0
file: spilo/postgres-appliance/scripts/postgres_backup.sh (https://github.com/zalando/spilo/blob/3.3-p1/postgres-appliance/scripts/postgres_backup.sh)
os: tested the backup script in container

```
root@db-2:/run# wal-g -v
wal-g version v3.0.0    4689e3a 2024.03.17_10:04:25     PostgreSQL

root@db-2:/run# uname -a
Linux db-2 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

root@db-2:/run# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
...
```

compose env
```yaml
      USE_WALG_BACKUP: "true"
      USE_WALG_RESTORE: "true"
      WALG_BACKUP_FROM_REPLICA: "true"
      WALG_SSH_PREFIX: "${BACKUP_SSH_PREFIX}"
      SSH_PORT: "${BACKUP_SSH_PORT}"
      SSH_USERNAME: "${BACKUP_SSH_USER}"
      SSH_PRIVATE_KEY_PATH: "${BACKUP_SSH_KEY}"
```

## My workaround

Edit the backup script sed regex
```
# from
done < <($WAL_E backup-list 2> /dev/null | sed '0,/^name\s*\(last_\)\?modified\s*/d')

# to
done < <($WAL_E backup-list 2> /dev/null | sed '0,/^backup_name\s*\(last_\)\?modified\s*/d')
```

Before modified
```
root@db-2:/home/postgres# wal-g backup-list
INFO: 2024/08/12 07:02:17.674772 List backups from storages: [default]
backup_name                   modified             wal_file_name            storage_name
base_0000003100000020000000DA 2024-08-01T01:01:26Z 0000003100000020000000DA default
base_00000031000000210000000A 2024-08-02T01:01:25Z 00000031000000210000000A default
...
```

After modified, the older backup is deleted
```
postgres@db-2:/scripts$ envdir "/run/etc/wal-e.d/env" /scripts/postgres_backup.sh "/home/postgres/pgdata/pgroot/data"
INFO: 2024/08/12 07:26:01.442420        will be deleted: basebackups_005/base_00000031000000210000003A/tar_partitions/part_004.tar.lz4, from storage: default
...

root@db-2:/run# wal-g backup-list
INFO: 2024/08/12 07:51:07.034572 List backups from storages: [default]
backup_name                   modified             wal_file_name            storage_name
base_000000320000002200000061 2024-08-07T01:01:19Z 000000320000002200000061 default
base_0000003600000023000000DC 2024-08-08T01:01:27Z 0000003600000023000000DC default
...
```

### PR DESCRIPTION
**Pull request by nickmansrob**
Fixes #1015 

Credits to @andrewfung729 for providing the fix.

Created a PR out of this because I also encountered this issue and needed a fix relatively quickly.

For the maintainers, could you give an estimate on when spilo gets released and when the postgres operator is also bumped? If this could take a while, I may create my own monkey patch until this is released.

Thanks!

### CODE REVIEW

**Comment by nickmansrob** [comment]
I also was wondering why the script does not use following command: `wal-g delete retain FULL $DAYS_TO_RETAIN`
This is probably an easier way instead of calculating the `$BEFORE` variable

**Review by MatzHilven — APPROVED** [review]

**Review by emrah83 — APPROVED** [review]
The new version of wal-g uses the header name "backup_name" instead of "name".  The regex script should be modified to adapt to this

**Comment by emrah83** [comment]
> Isn't this going to break `wal-e` because it still prints `name` in version `1.1.1`?

Haven't tested it with wal-e. If so, yes, this time wal-e user's won't have their backup files cleaned up.

**Comment by nickmansrob** [comment]
I updated my regex to be backwards compatible with wal-e.

**Comment by fgalind1** [comment]
any chance this would get approved and merged, we're facing also the same issue and tested that this fixes the issue

**Comment by Yingrjimsch** [comment]
If this is already touched, can we discuss if there is an option to have `BACKUP_NUM_TO_RETAIN` really be the number of backups and not the `DAYS_TO_RETAIN` this is confusing if I have multiple backups a day and then there are still more backups available then set by me via `BACKUP_NUM_TO_RETAIN`

**Comment by nickmansrob** [comment]
@Yingrjimsch I'd advise you to create a separate issue for this :)

**Comment by nickmansrob** [comment]
I'd like to see this merged asap, because I think it will take some time to get the version of spilo bumped on the operator, might want to use a custom build for the time being.

**Review by emrahbecer — APPROVED** [review]
Looks good to me. 
This change has better be merged asap because we cannot tolerate backup files to accumulate infinitely.

**Review by MatzHilven — APPROVED** [review]
LGTM!

**Comment by OlleLarsson** [comment]
Hi, would it be possible for either of you to take a look at this PR @hughcapet @FxKu :smiley: ?

**Comment by emrahbecer** [comment]
Great. I think we now have to wait for the next tag or release for the new  image.  Right?

**Comment by fgalind1** [comment]
any updates on this PR to get it merged that fixes the current branch? 👍

**Comment by FxKu** [comment]
Next week, I hope. End of november we always have to follow a stricter merge and deployment policy.

**Comment by hughcapet** [comment]
👍

**Comment by idanovinda** [comment]
👍

**Pull request merged**
