### PR TITLE
Enable possibility from restore from wal-e

### LINKED ISSUE #72: Restore with wal_e doesn't work
Missing:
```yaml
postgresql:
  create_replica_method:
  - wal_e
  - basebackup
```

So it always defaults to `basebackup` method

### PR DESCRIPTION
**Pull request by feikesteenbergen**
This possibility was accidentally removed in commit
55fd3aa121e2ded2654a2f4d4c4ff96bad061f40

Fixes #72

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
We also need to set the no_master: 1 for the wal-e, otherwise, it won't be considered when the master is not there.

**Comment by feikesteenbergen** [comment]
Would be something like this, right?:

```yaml
create_replica_method:
  - wal_e:
      no_master: 1
  - basebackup

**Comment by alexeyklyukin** [comment]
Nope, it should be a separate section under postgresql. It's already there actually.

**Comment by alexeyklyukin** [comment]
+1

**Pull request merged**
