### PR TITLE
Install wal-g from a precompiled bin

### PR DESCRIPTION
**Pull request by hughcapet**
- decrease build time
- fix the problem of missing brotli compression type after upgrade to WAL-G v3 (ref. https://github.com/wal-g/wal-g/pull/1379)

### CODE REVIEW

**Comment by macedigital** [comment]
Are there tests covering the check whether wal-g supports brotli ? 

It looks like we're relying on the fact that precompiled binaries (may have) enabled the optional brotli compression support by explicitly setting `USE_BROTLI=1` at build time.

**Comment by hughcapet** [comment]
Tests are currently covering our default configuration (not to use WAL-G for backup)
I tested this specific setup though (see the reverted commit)

**Comment by macedigital** [comment]
I think we should add tests for supported compression algorithms in general to Spilo, as `lz4` or `lzma` might be dropped at one time in future as well. This would help detecting issues with creating or restoring from backups early.

Something like: 

```bash
for algo in lz4 lzma brotli; do
  # ... verify backups can be created and restored from $algo
done
```

WDYT?

**Comment by hughcapet** [comment]
depending on how fast you need this fix to be rolled out and if you want to volunteer implementing it now:)

**Comment by macedigital** [comment]
> depending on how fast you need this fix to be rolled out and if you want to volunteer implementing it now:) (this can also be a follow-up PR)

Could be a follow-up PR as fixing applying a fix for the missing brotli support is urgent.

**Comment by macedigital** [comment]
:+1:

**Comment by hughcapet** [comment]
👍

**Pull request merged**
