### PR TITLE
Patroni 2.0

### LINKED ISSUE #468: Make etcd optional
Current version of Docker image is starting etcd regardless of if it's used or not. When using other dcs, etcd should not be started. @CyberDem0n Would you prefer a new env var to toggle this, or should it be derived by checking for presence of `ETCD_HOST`/`ETCD_HOSTS`/`ETCD_URL`?

### PR DESCRIPTION
**Pull request by CyberDem0n**
* wal-e 1.1.1
* wal-g 0.2.17
* timescaledb 1.7.3
* refactor DCS configuration (close #468)

### CODE REVIEW

**Comment by Jan-M** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Comment by Legogris** [comment]
Am I correct in understanding that keeping `KUBERNETES_BYPASS_API_SERVICE` should change nothing and unless kubernetes is set as provider, no kubernetes/etcd-specific functionality is being expected now?

**Comment by CyberDem0n** [comment]
It works only for cases when Patroni is using Kubernetes API for leader elections.
Also this parameters it is disabled by default.

**Pull request merged**
