### PR TITLE
CDP multi-arch image build

### PR DESCRIPTION
**Pull request by hughcapet**
Build multi-arch image and push it to Zalando Container Registry on every commit to master

### CODE REVIEW

**Comment by hughcapet** [comment]
@mmoscher it is for internal use only. OS will still be published in ghcr :)

**Comment by mmoscher** [comment]
> @mmoscher it is for internal use only. OS version will still be published in ghcr :)

@hughcapet ok, good to know 😃! but also cool to see that you now have a multi-arch registry internally

**Comment by FxKu** [comment]
:+1:

**Comment by hughcapet** [comment]
👍

**Pull request merged**
