### PR TITLE
Add environment variables

### PR DESCRIPTION
**Pull request by RafiaSabih**
Add Clone and Standby related environment variables.

### CODE REVIEW

**Comment by redbaron** [comment]
@RafiaSabih , can you help me find the code which uses these vars?

**Comment by Jan-M** [comment]
:+1:

**Comment by Jan-M** [comment]
https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py @redbaron this is where you will find most of the setup

**Comment by redbaron** [comment]
@Jan-M ,

> https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py @redbaron this is where you will find most of the setup


thanks for the link, I can't find references to variable like STANDBY_METHOD, which is set by recent change to postgres operator and also by this PR

**Comment by valer-cara** [comment]
Any updates here? I'm trying to use the remote standby feature in postgres-operator but it needs support from spilo. Thanks!

**Comment by avaczi** [comment]
@valer-cara https://github.com/zalando/spilo/pull/315 introduced the feature. Are you still missing something?  If so, could you be a bit more specific?

**Comment by valer-cara** [comment]
Indeed, no issues here. Probably a misconfiguration on my end. This is docs only.
Thanks for addressing!

**Comment by RafiaSabih** [comment]
:+1:

**Pull request closed without merging**
