### PR TITLE
Stick to the old version of pg_view

### PR DESCRIPTION
**Pull request by CyberDem0n**
until new version will become available via pip

### CODE REVIEW

**Comment by a1exsh** [comment]
:+1:

**Comment by alexeyklyukin** [comment]
Hm... turns out we didn't release the 9.6 compatible pg_view versions. Will fix and let you know.

**Comment by alexeyklyukin** [comment]
Done, please, do pip install pg_view --upgrade, I've released 1.4 to fix PostgreSQL 9.6 incompatibility.

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
