### PR TITLE
Use relevant params in pgqd ini file

### PR DESCRIPTION
**Pull request by hughcapet**
Seems, config file didn't set anything for a long time (if ever did).

### CODE REVIEW

**Comment by mblsf** [comment]
I think the new parameters logfile and pidfile are also mandatory

**Comment by hughcapet** [comment]
@mblsf as far as I see, `pidfile` is only required for daemonizing. But I think `logfile` is worth using together with `pgqd -q` in order to avoid mixing up pgqd and Patroni output in container logs, thanks for pointing to it.

**Comment by sdudoladov** [comment]
:+1:

**Comment by hughcapet** [comment]
👍

**Pull request merged**
