### PR TITLE
Add pgvector extension

### PR DESCRIPTION
**Pull request by drivebyer**
support https://github.com/zalando/spilo/issues/894

The build image here: https://github.com/drivebyer/spilo/pkgs/container/spilo-15 with tag v0.0.2

### CODE REVIEW

**Comment by hughcapet** [comment]
Why have you decided to only include it for PG15+?

**Comment by hughcapet** [comment]
Btw, it actually is [available in the postgresql apt repo](https://github.com/pgvector/pgvector#apt). We prefer to install extensions from there when it is possible

**Comment by drivebyer** [comment]
> Why have you decided to only include it for PG15+?

I saw the spilo it built only for PGVERSION 15 now(https://github.com/zalando/spilo/pkgs/container/spilo-15). Do we need build for early PG version?

**Comment by hughcapet** [comment]
this image includes PG version 15 + [the old versions](https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L51)  ([DEB_PG_SUPPORTED_VERSIONS](https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L54))

extensions are provided for [as much as possible PG versions from this list ](https://github.com/zalando/spilo/blob/master/postgres-appliance/build_scripts/base.sh#L75)

**Comment by drivebyer** [comment]
> this image includes PG version 15 + [the old versions](https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L51) ([DEB_PG_SUPPORTED_VERSIONS](https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L54))
> 
> extensions are provided for [as much as possible PG versions from this list ](https://github.com/zalando/spilo/blob/master/postgres-appliance/build_scripts/base.sh#L75)

Ohh I see. 

I fixed the pr PTAL @hughcapet 

The built image in https://github.com/drivebyer/spilo/pkgs/container/spilo-15 with tag v0.0.2

**Comment by hughcapet** [comment]
lgtm, we will merge it early next week

**Comment by sdudoladov** [comment]
:+1:

**Comment by hughcapet** [comment]
👍

**Comment by hughcapet** [comment]
Merged. Thank you, @drivebyer

**Comment by NicolaiSchmid** [comment]
When will this be released as a docker image?

**Comment by drivebyer** [comment]
pg_vector available since spilo-15:3.1-p1

**Comment by shixiaofeia** [comment]
> available in the postgresql apt repo

I am using version 3.1-p1 and still don't have this extension. Do you have an installation tutorial?

**Pull request merged**
