### PR TITLE
Add timeline_id parameter for restore

### PR DESCRIPTION
**Pull request by Sudeepta92**
TIMELINE_ID is added as a dynamic parameter to enable selection of timeline id for recovery.

Issue: https://github.com/zalando/spilo/issues/712

### CODE REVIEW

**Review by CyberDem0n — COMMENTED** [review]
1. I believe the `CLONE_TARGET_TIMELINE` would be a better name (to match the already used naming pattern).
2. Please also update the documentation.

**Comment by FxKu** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Comment by Sudeepta92** [comment]
Great! Also, thanks to you guys for the ongoing development & support!

**Comment by Sudeepta92** [comment]
Also, will this be included in the next Spilo release or..?

**Pull request merged**
